name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install dependencies & build & deploy
        run: |

          git config --global user.email "dev@paketmutfak.com.tr"
          git config --global user.name "PaketMutfak"

          npm install
          npm run build
          npm run gh-pages
